launch_container: update sample config file name

diff --git a/deployment/launch_container b/deployment/launch_container
--- a/deployment/launch_container
+++ b/deployment/launch_container
@@ -40,7 +40,7 @@ else
 fi
 
 if [ -z "$CONFIG_FILE" ]; then
-    echo "ERROR: please provide a config file or set LAUNCH_CONTAINER_CONFIG_FILE='path/to/config.file'" 1>&2
+    echo "ERROR: please provide a config file or set LAUNCH_CONTAINER_CONFIG_FILE='path/to/configfile.conf'" 1>&2
     exit 2
 fi
 
